name: Test

on:
  push:
  pull_request:

jobs:
  go-tests-on-linux:
    name: "Test (linux)"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang:
          - 1.15.x
          - 1.16.x
          #- tip
    env:
      OS: ubuntu-latest
      GOLANG: ${{ matrix.golang }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      - name: Check go.mod and go.sum
        run: |
          go mod tidy -v
          git --no-pager diff go.mod go.sum
          git --no-pager diff --quiet go.mod go.sum
      - name: Run fast tests multiple times
        run: make test

  go-tests-on-windows:
    name: "Test (windows)"
    runs-on: windows-latest
    strategy:
      matrix:
        golang: ['1.16.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      - name: Check go.mod and go.sum
        run: |
          go mod tidy -v
          git --no-pager diff go.mod go.sum
          git --no-pager diff --quiet go.mod go.sum
      - name: Run fast tests multiple times
        run: make test
